In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
print(device)

cpu


In [4]:
a = torch.tensor([1])
a

tensor([1])

In [8]:
ar = torch.zeros(3)
ar  # Above 3 represents the rows only, no cols

tensor([0., 0., 0.])

In [7]:
a0 = torch.zeros(1, 2)  # 1 is row and 2 is col
print(a0)
a0.shape

tensor([[0., 0.]])


torch.Size([1, 2])

In [11]:
a1s = torch.ones(3, 5)
a1s  # ones of 3rows and 5 cols 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
arand = torch.rand(5, 3)  # Random number of 5 rows and 3 cols
arand

tensor([[0.9306, 0.4336, 0.5672],
        [0.8167, 0.4865, 0.8283],
        [0.2016, 0.6393, 0.0815],
        [0.1990, 0.2346, 0.5004],
        [0.0688, 0.4652, 0.9288]])

In [13]:
emp = torch.empty(5, 2)  # empty tensors, minimum vals of 5 rows and 2 cols
emp  # one can observe the e-10 to e-50 in the output

tensor([[-1.6733e+32,  2.0179e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [14]:
# getting a random series of numbers between the 
randa = torch.randint(low=15, high=25, size=(5, 7))
randa

tensor([[20, 24, 24, 15, 20, 19, 21],
        [19, 15, 19, 16, 21, 17, 20],
        [15, 22, 21, 24, 23, 22, 19],
        [23, 24, 22, 24, 23, 21, 24],
        [16, 22, 22, 18, 18, 20, 22]])

In [15]:
# looking at boolean

n = torch.tensor(62.51)
print(n < 0)
print(n > 0)

tensor(False)
tensor(True)


In [17]:
print((n < 0).long())
print((n > 0).long())

tensor(0)
tensor(1)


In [18]:
# using where in torch
torch.where(torch.tensor(False), torch.tensor(0), torch.tensor(1))

tensor(1)

In [29]:
torch.where(randa > 20, torch.tensor(567), torch.tensor(63)) 

tensor([[ 63, 567, 567,  63,  63,  63, 567],
        [ 63,  63,  63,  63, 567,  63,  63],
        [ 63, 567, 567, 567, 567, 567,  63],
        [567, 567, 567, 567, 567, 567, 567],
        [ 63, 567, 567,  63,  63,  63, 567]])

In [34]:
## Understand how the rows and cols are being created
## Its necessary to understand, for later manipulation of cols and rows
## Vector Math, Matrix Math and Tensor Math all depends on Rows & Cols
## Much of the Prediction, Classification rely on simple vector math operations

In [31]:
n_3r = torch.tensor([5.7, 62, 46])
n_3r.shape  # only rows

torch.Size([3])

In [32]:
n_3c = torch.tensor([[5],[7],[1]])
n_3c.shape # single col with 3 rows

torch.Size([3, 1])

In [33]:
n_3rc = torch.tensor([[3, 4, 5]])
n_3rc.shape  # 3 cols with single row

torch.Size([1, 3])

In [35]:
# using _like methods 
a0like = torch.zeros_like(randa)
a0like

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])

In [36]:
a1like = torch.ones_like(randa)
a1like

tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]])

In [41]:
# making tensors of random numbers
try:
    arandlike = torch.rand_like(torch.tensor([1, 5, 7]))
except Exception as e:
    print(e)

arandlike = torch.rand_like(torch.tensor([1.5, 5.2, 77.5]))
arandlike

# https://stackoverflow.com/questions/76171206/pytorch-runtimeerror-check-uniform-bounds-not-implemented-for-int

"check_uniform_bounds" not implemented for 'Long'


tensor([0.9072, 0.7709, 0.5886])

In [44]:
# linspace is similar to linrange in numpy
import numpy as np
rangenum = np.linspace(5, 19, 10)
rangenum

array([ 5.        ,  6.55555556,  8.11111111,  9.66666667, 11.22222222,
       12.77777778, 14.33333333, 15.88888889, 17.44444444, 19.        ])

In [45]:
rangets = torch.linspace(5, 19, 10)
rangets

tensor([ 5.0000,  6.5556,  8.1111,  9.6667, 11.2222, 12.7778, 14.3333, 15.8889,
        17.4444, 19.0000])

In [46]:
# identity matrices
h = torch.eye(5)
h

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [47]:
# generating multi-dimensional tensors
h1 = torch.rand(size=[199, 57, 66])
h1.shape

torch.Size([199, 57, 66])

In [50]:
h1[0][0].shape

torch.Size([66])

In [54]:
# operating on the tensors and changing shape

ys = torch.rand(3)
ys  # no rows are cols, just 3 elements

tensor([0.1886, 0.1729, 0.0488])

In [60]:
# starting with unsqueeze

In [52]:
us = ys.unsqueeze(dim=0)
us.shape  # becomes 1 row with 3 cols

torch.Size([1, 3])

In [55]:
us = ys.unsqueeze(dim=1)
us.shape  # become 3 rows and 1 col 

torch.Size([3, 1])

In [56]:
ys1 = torch.rand(3, 2)  # 3 rows and 2 cols
ys1

tensor([[0.0303, 0.9195],
        [0.3510, 0.4542],
        [0.1580, 0.2058]])

In [58]:
ys1.unsqueeze(dim=0).shape

torch.Size([1, 3, 2])

In [59]:
ys1.unsqueeze(dim=1).shape

torch.Size([3, 1, 2])

In [61]:
j = torch.tensor([0.2, 8.5, 3.25])
# Multinomial is an algebraic expression which contains two or more unlike terms
# Polynomial has more than 3 unlike, so it is a category of multinomial
# nominal means terms, that is twisted to be nomial. so it is "many Terms"
samples = torch.multinomial(j, 10, replacement=True)
samples

tensor([1, 2, 1, 1, 1, 2, 2, 1, 1, 1])

In [62]:
m2 = torch.tensor([[5, 0, 1],
                   [8, 10, 9],
                   [0.5, 0.7, 0.9]], dtype=torch.float32)
m2

tensor([[ 5.0000,  0.0000,  1.0000],
        [ 8.0000, 10.0000,  9.0000],
        [ 0.5000,  0.7000,  0.9000]])

In [63]:
p2 = torch.multinomial(m2, 5, True)
p2

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0],
        [0, 0, 2, 1, 1]])

In [64]:
k = torch.tensor([1, 2, 5, 7])
l = torch.tensor([5])

m = torch.tensor(5)
print(k)
print(l)
print(m)

tensor([1, 2, 5, 7])
tensor([5])
tensor(5)


In [65]:
# catenate on rows
outcat = torch.cat((k, l), dim=0)
outcat

tensor([1, 2, 5, 7, 5])

In [68]:
# catenate on cols
try:
    outcol = torch.cat((k, m), dim=1)
    outcol
except Exception as e:
    print(e)

p = torch.randint(low=5, high=10, size=(2, 5))
q = torch.randint(low=10, high=100, size=(2, 5))
outcol = torch.cat((p, q), dim=1)
outcol

zero-dimensional tensor (at position 1) cannot be concatenated


tensor([[ 5,  7,  7,  7,  6, 36, 28, 32, 10, 89],
        [ 5,  7,  8,  5,  5, 14, 46, 37, 95, 45]])

In [70]:
# stackin the tensors

s1 = torch.arange(0, 5)  # all tensors are 1r and 5c shape
s2 = torch.arange(1, 6)
s3 = torch.arange(2, 7)
s4 = torch.arange(4, 9)
try:
    s5 = torch.stack(s1, s2, s3, s4)
except Exception as e:
    print(e)

s5 = torch.stack([s1, s2, s3, s4])
s5.shape

stack() takes from 1 to 2 positional arguments but 4 were given


torch.Size([4, 5])

In [72]:
s5 = torch.stack([s1, s2, s3, s4], dim=1)
s5.shape

torch.Size([5, 4])

In [81]:
tlo = torch.tril(torch.ones(5, 5) * 5)
tlo  # Only lower has the values above 0

tensor([[5., 0., 0., 0., 0.],
        [5., 5., 0., 0., 0.],
        [5., 5., 5., 0., 0.],
        [5., 5., 5., 5., 0.],
        [5., 5., 5., 5., 5.]])

In [82]:
tup = torch.triu(torch.ones(5, 5) * 5)
tup  # Only lower has the values above 0

tensor([[5., 5., 5., 5., 5.],
        [0., 5., 5., 5., 5.],
        [0., 0., 5., 5., 5.],
        [0., 0., 0., 5., 5.],
        [0., 0., 0., 0., 5.]])

In [83]:
# creating a masks
maskout = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0,
                                        float('-inf'))
maskout

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [84]:
torch.exp(maskout)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [86]:
# transpose

input = torch.rand(5, 6, 2)
print(input.shape)
inputout = input.transpose(0, 1)
inputout.shape

torch.Size([5, 6, 2])


torch.Size([6, 5, 2])

In [87]:
input.shape

torch.Size([5, 6, 2])