Notebook introduces the Embeddings and their use cases 

It all starts with Data, in this case the data is taken from the https://faq.ssa.gov/en-US/

Note, Embedding is a process of converting a word or a number into a vector of certain dimensions
Tokenizer and Embedding models are not same. They are different. 

Tokenizers are functions written in python that take a corpus of data and returns a dictionary-id map. Based on which the tokenizers, work on the sentences.

Embedding models are Neural Networks coded in Torch/TF/Jax/Flax that are used for creating vectors 

In [1]:
# we have to work with sentence transformers library. 

from sentence_transformers import SentenceTransformer, util

model_id = "sentence-transformers/all-MiniLM-L6-v2"
model_embedding = SentenceTransformer(model_id)

In [2]:
texts = ["How do I get a replacement Medicare card?",
        "What is the monthly premium for Medicare Part B?",
        "How do I terminate my Medicare Part B (medical insurance)?",
        "How do I sign up for Medicare?",
        "Can I sign up for Medicare Part B if I am working and have health insurance through an employer?",
        "How do I sign up for Medicare Part B if I already have Part A?",
        "What are Medicare late enrollment penalties?",
        "What is Medicare and who can get it?",
        "How can I get help with my Medicare Part A and Part B premiums?",
        "What are the different parts of Medicare?",
        "Will my Medicare premiums be higher because of my higher income?",
        "What is TRICARE ?",
        "Should I sign up for Medicare Part B if I have Veterans' Benefits?"]

In [3]:
model_embedding.to('cuda')

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [5]:
texts_tokenized = model_embedding.tokenize(texts=texts[0],)

In [6]:
texts_tokenized

{'input_ids': tensor([[ 101, 1044,  102],
         [ 101, 1051,  102],
         [ 101, 1059,  102],
         [ 101,  102,    0],
         [ 101, 1040,  102],
         [ 101, 1051,  102],
         [ 101,  102,    0],
         [ 101, 1045,  102],
         [ 101,  102,    0],
         [ 101, 1043,  102],
         [ 101, 1041,  102],
         [ 101, 1056,  102],
         [ 101,  102,    0],
         [ 101, 1037,  102],
         [ 101,  102,    0],
         [ 101, 1054,  102],
         [ 101, 1041,  102],
         [ 101, 1052,  102],
         [ 101, 1048,  102],
         [ 101, 1037,  102],
         [ 101, 1039,  102],
         [ 101, 1041,  102],
         [ 101, 1049,  102],
         [ 101, 1041,  102],
         [ 101, 1050,  102],
         [ 101, 1056,  102],
         [ 101,  102,    0],
         [ 101, 1049,  102],
         [ 101, 1041,  102],
         [ 101, 1040,  102],
         [ 101, 1045,  102],
         [ 101, 1039,  102],
         [ 101, 1037,  102],
         [ 101, 1054,  102],
 

In [12]:
texts_embed01 = model_embedding.encode(texts[0], convert_to_tensor=True)
texts_embed01.shape

torch.Size([384])

In [13]:
texts_embed02 = model_embedding.encode(texts[1], convert_to_tensor=True)
texts_embed02.shape

torch.Size([384])

In [14]:
from sentence_transformers.util import pytorch_cos_sim

In [15]:
similarity = pytorch_cos_sim(texts_embed01, texts_embed02)
similarity

tensor([[0.4886]], device='cuda:0')

In [5]:
embedding_texts = model_embedding.encode(texts)
embedding_texts.shape

(13, 384)

In [6]:
from pandas import DataFrame

embed_df = DataFrame(embedding_texts)

In [18]:
embed_df

0         1         2    ...       381       382       383
0  -0.023889  0.055259 -0.011655  ...  0.005778  0.034098 -0.006889
1  -0.012688  0.046874 -0.010502  ... -0.023103 -0.002785  0.010474
2   0.000494  0.119412  0.005230  ...  0.016877 -0.023861  0.005264
3  -0.029711  0.023298 -0.057041  ...  0.003617  0.033993 -0.010255
4  -0.025628  0.070389 -0.017380  ... -0.040412  0.083346  0.026855
5  -0.022656  0.021160  0.005105  ...  0.059089 -0.017509  0.007166
6  -0.002911  0.060791 -0.009176  ... -0.073420  0.016235 -0.000244
7  -0.080526  0.059888 -0.048847  ... -0.005989  0.134562  0.034817
8  -0.034388  0.072501  0.014440  ...  0.000578 -0.025124  0.034191
9  -0.005964  0.025044 -0.003182  ...  0.029937  0.070214  0.041565
10 -0.039008 -0.010609 -0.007383  ... -0.083904  0.037684  0.002314
11 -0.095983 -0.063012 -0.116906  ...  0.005498  0.152892  0.024720
12 -0.011600  0.056510  0.016624  ... -0.029012  0.001888 -0.000133

[13 rows x 384 columns]

In [7]:
embed_df['texts'] = texts

In [8]:
embed_df.to_csv("embed_text.csv",index=False)

In [11]:
# pushing the dataset to huggingface hub

from huggingface_hub import notebook_login
notebook_login()

In [12]:
from datasets import load_dataset, Dataset

In [14]:
embed_ds = Dataset.from_pandas(embed_df)
embed_ds

Dataset({
    features: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', 

In [15]:
embed_ds = embed_ds.train_test_split(train_size=0.8)

In [16]:
embed_ds

DatasetDict({
    train: Dataset({
        features: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150',

In [17]:
dataset_path = "Kamaljp/embed_texts"
embed_ds.push_to_hub(dataset_path)

Pushing dataset shards to the dataset hub:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Pushing dataset shards to the dataset hub:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

In [24]:
# there are some models with mandatory prompts,

allmini = "sentence-transformers/all-MiniLM-L6-v2"

prompts = {
    "classification": "Classify the following text:",
    "retrieval": "Retrieve Semantically Similar text:",
    "Clustering": "Identify the topic or theme based on the text:"
}

In [25]:
multiling_model = SentenceTransformer(
    model_name_or_path=allmini,
    prompts=prompts
)

In [26]:
# during embedding, the following process is followed

embeddings = multiling_model.encode("There are many good looking places",
                                    prompt_name='retrieval')

In [33]:
# We can use the Transformers AutoClasses, will require additional steps to access the embedding
# We cannot dismantle the model so we need to dissect the model output

from transformers import AutoTokenizer, AutoModel

In [31]:
tokenizer = AutoTokenizer.from_pretrained(allmini)
model = AutoModel.from_pretrained(allmini)

In [35]:
sentences = [
    "This framework generate embeddings for each input sentence",
    "Sentences are passed as a list of strings",
    "The quick brown fox jupms over the lazy dog.",
]

In [37]:
encode_sentence = tokenizer(sentences, padding=True, truncation=True, max_length=128, return_tensors='pt') 

In [39]:
encode_sentence.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [40]:
# When getting the inference, the encoded tokens are sent into the models for processing
# first step in the model is embedding
import torch

with torch.no_grad():  # We don't want the model to calculate the gradient, when making this pass
    model_out = model(**encode_sentence)

In [42]:
type(model_out)  # observe the type of the model_out

transformers.modeling_outputs.BaseModelOutputWithPoolingAndCrossAttentions

In [44]:
token_embeds = model_out[0]
token_embeds.shape  # Try to explain the shape, by relooking at the earlier steps

torch.Size([3, 14, 384])

#### Next mean-pooling is not mandatory

In [47]:
# lets seperate the attn_mask
attn_mask = encode_sentence["attention_mask"]
attn_mask.shape

torch.Size([3, 14])

In [49]:
# Starting the process of Mean Pooling manually. This step is done for model inference
# expanding the attn_masks
attn_mask_expanded = attn_mask.unsqueeze(-1).expand(token_embeds.size()).float()
# attn_mask_expanded

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [50]:
sum_embeds = torch.sum(token_embeds * attn_mask_expanded , 1)

In [51]:
sum_mask = torch.clamp(attn_mask_expanded.sum(1), min=1e-9)

In [52]:
mean_pooled = sum_embeds / sum_mask
mean_pooled

tensor([[-0.0923, -0.2241, -0.0747,  ...,  0.5802,  0.6137, -0.2178],
        [ 0.2897,  0.2838,  0.2554,  ...,  0.2671,  0.3355, -0.1703],
        [ 0.1504,  0.4607,  0.2637,  ...,  0.0908,  0.3025,  0.3073]])

#### Some Tasks with Embedding

##### text similarity

In [57]:
# Text Similarity

sentences2 = [
    'There is more to embeddings than it meets the eyes',
    'Every object in the Neural Network world have a rich and varied back story',
    'when there are instances, that means there has to be blueprints of them lying around'
]
sentences = ['This framework generate embeddings for each input sentence',
 'Sentences are passed as a list of strings',
 'The quick brown fox jupms over the lazy dog.']

In [59]:
embed = model_embedding.encode(sentences)
embed2 = model_embedding.encode(sentences2)

In [60]:
# get the cosine scores
cos_scores = util.cos_sim(embed2, embed)
cos_scores  # the scores for each sentence in one embeding list is compared with another embeding list
# So there will be a matrix

tensor([[0.3594, 0.1727, 0.1343],
        [0.3569, 0.1764, 0.1245],
        [0.1035, 0.1637, 0.1032]])

##### semantic search

Symmetric search: Query and the retrieved sentences are having the same length
[link](https://www.sbert.net/docs/pretrained_models.html#sentence-embedding-models)

Assymetric search: Query is smaller in size, while the sentences are longer, like paras
[link](https://www.sbert.net/docs/pretrained-models/msmarco-v3.html)

In [61]:
corpus = [
    "A man is eating food.",
    "A man is eating a piece of bread.",
    "The girl is carrying a baby.",
    "A man is riding a horse.",
    "A woman is playing violin.",
    "Two men pushed carts through the woods.",
    "A man is riding a white horse on an enclosed ground.",
    "A monkey is playing drums.",
    "A cheetah is running behind its prey.",
]

# Query sentences:
queries = [
    "A man is eating pasta.",
    "Someone in a gorilla costume is playing a set of drums.",
    "A cheetah chases prey on across a field.",
]


In [72]:
from sentence_transformers.util import (
    normalize_embeddings,
    dot_score,
    semantic_search
)

In [62]:
corpus_embeddings = model_embedding.encode(corpus, convert_to_tensor=True)

In [63]:
corpus_embeddings =  corpus_embeddings.to('cuda')

In [65]:
corpus_embeddings.shape

torch.Size([9, 384])

In [70]:
# normalized corpus embeddings make it simple to calculat the dot-pdt
corpus_embeddings = normalize_embeddings(corpus_embeddings)
corpus_embeddings

tensor([[ 0.0332,  0.0044, -0.0063,  ...,  0.0692, -0.0246, -0.0376],
        [ 0.0525,  0.0552, -0.0112,  ..., -0.0162, -0.0602, -0.0412],
        [-0.0363, -0.0357, -0.0272,  ..., -0.0386,  0.1057, -0.0013],
        ...,
        [ 0.0370,  0.0226,  0.0496,  ..., -0.0031,  0.0489,  0.0167],
        [ 0.0235, -0.0585,  0.0560,  ...,  0.0584,  0.0377,  0.0410],
        [ 0.0228,  0.1041, -0.0340,  ...,  0.0029,  0.0386,  0.0438]],
       device='cuda:0')

In [71]:
query_embeddings = model_embedding.encode(queries, convert_to_tensor=True)
query_embeddings = normalize_embeddings(query_embeddings.to('cuda'))
query_embeddings

tensor([[-0.0116, -0.0508, -0.0217,  ...,  0.0822,  0.0099, -0.0394],
        [-0.0357,  0.0168,  0.0448,  ...,  0.0249,  0.0653, -0.0112],
        [ 0.0544,  0.0540, -0.0037,  ...,  0.0325,  0.0219,  0.0621]],
       device='cuda:0')

In [73]:
semantic_search = semantic_search(query_embeddings, corpus_embeddings, score_function=dot_score)

In [74]:
semantic_search

[[{'corpus_id': 0, 'score': 0.7035486698150635},
  {'corpus_id': 1, 'score': 0.5271987318992615},
  {'corpus_id': 3, 'score': 0.18889553844928741},
  {'corpus_id': 6, 'score': 0.10469923168420792},
  {'corpus_id': 8, 'score': 0.09803037345409393},
  {'corpus_id': 7, 'score': 0.08189043402671814},
  {'corpus_id': 4, 'score': 0.033593956381082535},
  {'corpus_id': 5, 'score': -0.059434838593006134},
  {'corpus_id': 2, 'score': -0.08980069309473038}],
 [{'corpus_id': 7, 'score': 0.6432533264160156},
  {'corpus_id': 4, 'score': 0.25641557574272156},
  {'corpus_id': 3, 'score': 0.1388726532459259},
  {'corpus_id': 6, 'score': 0.11909151822328568},
  {'corpus_id': 8, 'score': 0.10798682272434235},
  {'corpus_id': 0, 'score': 0.06300687044858932},
  {'corpus_id': 2, 'score': 0.02465788647532463},
  {'corpus_id': 1, 'score': 0.021566985175013542},
  {'corpus_id': 5, 'score': -0.08950325846672058}],
 [{'corpus_id': 8, 'score': 0.8253214359283447},
  {'corpus_id': 0, 'score': 0.1398952305316925}

##### Many real world problems can be solved using the above embedding models

- Using ANN to search for getting the context for the RAG

- Retrieve Similar questions, or similar problems, similar products based on something chosen by the user

- Ranking the retrieved snippets for relevancy is another interesting task that can enrich the search process-

- Clustering the sentences into topics or ideas

- Paraphrase mining of large corpus texts with similar meaning or idea

- Image Search using the embedded data of the image

##### Retrieve & Re-Rank

We will be using the CrossEncoder modlel cross-encoder/ms-marco-MiniLM-L-6-v2

In [ ]:
# !pip install rank_bm25

In [75]:
import json
from sentence_transformers import SentenceTransformer, CrossEncoder, util
import gzip
import os
import torch

In [78]:
multi_qa = "multi-qa-MiniLM-L6-cos-v1"
bi_encoder = SentenceTransformer(multi_qa)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [91]:
cross_enc = "cross-encoder/ms-marco-MiniLM-L-6-v2"

cross_encoder = CrossEncoder(cross_enc)

In [80]:
wikipedia_filepath = 'simplewiki-2020-11-01.jsonl.gz'

if not os.path.exists(wikipedia_filepath):
    util.http_get('http://sbert.net/datasets/simplewiki-2020-11-01.jsonl.gz', wikipedia_filepath)

  0%|          | 0.00/50.2M [00:00<?, ?B/s]

In [81]:
passages = []
with gzip.open(wikipedia_filepath, 'rt', encoding='utf8') as fIn:
    for line in fIn:
        data = json.loads(line.strip())

        #Add all paragraphs
        #passages.extend(data['paragraphs'])

        #Only add the first paragraph
        passages.append(data['paragraphs'][0])

print("Passages:", len(passages))

Passages: 169597


In [82]:
bi_encoder = bi_encoder.to("cuda")  # In CPU will take long time, items/sec rate will be 10/ 15. With 

In [83]:
# embed the entire 170K passages with bi-encoder
corpus_embeding = bi_encoder.encode(passages, convert_to_tensor=True, show_progress_bar=True, device='cuda')

Batches:   0%|          | 0/5300 [00:00<?, ?it/s]

In [84]:
from rank_bm25 import BM25Okapi
from sklearn.feature_extraction import _stop_words
import string
from tqdm.autonotebook import tqdm
import numpy as np


In [85]:
# We lower case our text and remove stop-words from indexing
def bm25_tokenizer(text):
    tokenized_doc = []
    for token in text.lower().split():
        token = token.strip(string.punctuation)

        if len(token) > 0 and token not in _stop_words.ENGLISH_STOP_WORDS:
            tokenized_doc.append(token)
    return tokenized_doc


In [86]:
tokenized_corpus = []
for passage in tqdm(passages):
    tokenized_corpus.append(bm25_tokenizer(passage))

bm25 = BM25Okapi(tokenized_corpus)

  0%|          | 0/169597 [00:00<?, ?it/s]

In [92]:
# This function will search all wikipedia articles for passages that
# answer the query
def search(query):
    print("Input question:", query)

    ##### BM25 search (lexical search) #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -5)[-5:]
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n]
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)
    
    print("Top-3 lexical search (BM25) hits")
    for hit in bm25_hits[0:3]:
        print("\t{:.3f}\t{}".format(hit['score'], passages[hit['corpus_id']].replace("\n", " ")))

    ##### Semantic Search #####
    # Encode the query using the bi-encoder and find potentially relevant passages
    question_embedding = bi_encoder.encode(query, convert_to_tensor=True)
    question_embedding = question_embedding.cuda()
    hits = util.semantic_search(question_embedding, corpus_embeddings, top_k=32)
    hits = hits[0]  # Get the hits for the first query

    ##### Re-Ranking ##### Try to explain this part 
    # Now, score all retrieved passages with the cross_encoder
    cross_inp = [[query, passages[hit['corpus_id']]] for hit in hits]
    cross_scores = cross_encoder.predict(cross_inp)

    # Sort results by the cross-encoder scores
    for idx in range(len(cross_scores)):
        hits[idx]['cross-score'] = cross_scores[idx]

    # Output of top-5 hits from bi-encoder
    print("\n-------------------------\n")
    print("Top-3 Bi-Encoder Retrieval hits")
    hits = sorted(hits, key=lambda x: x['score'], reverse=True)
    for hit in hits[0:3]:
        print("\t{:.3f}\t{}".format(hit['score'], passages[hit['corpus_id']].replace("\n", " ")))

    # Output of top-5 hits from re-ranker
    print("\n-------------------------\n")
    print("Top-3 Cross-Encoder Re-ranker hits")
    hits = sorted(hits, key=lambda x: x['cross-score'], reverse=True)
    for hit in hits[0:3]:
        print("\t{:.3f}\t{}".format(hit['cross-score'], passages[hit['corpus_id']].replace("\n", " ")))

In [93]:
search(query="Who is the president of India")

Input question: Who is the president of India
Top-3 lexical search (BM25) hits
	14.509	The Vice President of India is the second-highest constitutional official in India, after the President.
	13.316	Fakhruddin Ali Ahmed was the fifth President of India from 1974 to 1977 and also the 2nd President of India to die in office.
	11.866	The President of India is the head of state of the Republic of India. The current president, Ram Nath Kovind, who was sworn in on 25 July 2017. He succeeded Pranab Mukherjee. The President resides in an estate known as the Rashtrapati Bhavan in New Delhi.

-------------------------

Top-3 Bi-Encoder Retrieval hits
	0.119	Ted Cassidy (July 31, 1932 - January 16, 1979) was an American actor. He was best known for his roles as Lurch and Thing on "The Addams Family".
	0.077	Aileen Carol Wuornos Pralle (born Aileen Carol Pittman; February 29, 1956 – October 9, 2002) was an American serial killer. She was born in Rochester, Michigan. She confessed to killing six m

In [94]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

# Single list of sentences - Possible tens of thousands of sentences
sentences = [
    "The cat sits outside",
    "A man is playing guitar",
    "I love pasta",
    "The new movie is awesome",
    "The cat plays in the garden",
    "A woman watches TV",
    "The new movie is so great",
    "Do you like pizza?",
]

paraphrases = util.paraphrase_mining(model, sentences)

for paraphrase in paraphrases[0:10]:
    score, i, j = paraphrase
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences[i], sentences[j], score))

The new movie is awesome 		 The new movie is so great 		 Score: 0.8939
The cat sits outside 		 The cat plays in the garden 		 Score: 0.6788
I love pasta 		 Do you like pizza? 		 Score: 0.5096
I love pasta 		 The new movie is so great 		 Score: 0.2560
I love pasta 		 The new movie is awesome 		 Score: 0.2440
A man is playing guitar 		 The cat plays in the garden 		 Score: 0.2105
The new movie is awesome 		 Do you like pizza? 		 Score: 0.1969
The new movie is so great 		 Do you like pizza? 		 Score: 0.1692
The cat sits outside 		 A woman watches TV 		 Score: 0.1310
The cat plays in the garden 		 Do you like pizza? 		 Score: 0.0900
