In [1]:
movies_path = '/Users/apple/Desktop/KamalRaj/Assignments/assignment_data/Movies.csv'

In [53]:
with open(movies_path, 'r') as f:
    text = f.read()
text

'\ufeffMovie ID,Movie Title,Release Year,Runtime,Budget,Box Office\n1,Harry Potter and the Philosopher\'s Stone,2001,152,"$125,000,000 ","$1,002,000,000 "\n2,Harry Potter and the Chamber of Secrets,2002,161,"$100,000,000 ","$880,300,000 "\n3,Harry Potter and the Prisoner of Azkaban,2004,142,"$130,000,000 ","$796,700,000 "\n4,Harry Potter and the Goblet of Fire,2005,157,"$150,000,000 ","$896,400,000 "\n5,Harry Potter and the Order of the Phoenix,2007,138,"$150,000,000 ","$942,000,000 "\n6,Harry Potter and the Half-Blood Prince,2009,153,"$250,000,000 ","$943,200,000 "\n7,Harry Potter and the Deathly Hallows Part 1,2010,146,"$200,000,000 ","$976,900,000 "\n8,Harry Potter and the Deathly Hallows Part 2,2011,130,"$250,000,000 ","$1,342,000,000 "\n'

In [56]:
l1 = []
for i in text.split('\n'):
    l1.append(i.split(','))
l1

[['\ufeffMovie ID',
  'Movie Title',
  'Release Year',
  'Runtime',
  'Budget',
  'Box Office'],
 ['1',
  "Harry Potter and the Philosopher's Stone",
  '2001',
  '152',
  '"$125',
  '000',
  '000 "',
  '"$1',
  '002',
  '000',
  '000 "'],
 ['2',
  'Harry Potter and the Chamber of Secrets',
  '2002',
  '161',
  '"$100',
  '000',
  '000 "',
  '"$880',
  '300',
  '000 "'],
 ['3',
  'Harry Potter and the Prisoner of Azkaban',
  '2004',
  '142',
  '"$130',
  '000',
  '000 "',
  '"$796',
  '700',
  '000 "'],
 ['4',
  'Harry Potter and the Goblet of Fire',
  '2005',
  '157',
  '"$150',
  '000',
  '000 "',
  '"$896',
  '400',
  '000 "'],
 ['5',
  'Harry Potter and the Order of the Phoenix',
  '2007',
  '138',
  '"$150',
  '000',
  '000 "',
  '"$942',
  '000',
  '000 "'],
 ['6',
  'Harry Potter and the Half-Blood Prince',
  '2009',
  '153',
  '"$250',
  '000',
  '000 "',
  '"$943',
  '200',
  '000 "'],
 ['7',
  'Harry Potter and the Deathly Hallows Part 1',
  '2010',
  '146',
  '"$200',
  '000'

In [59]:
dict1 = {}
dict1.keys = l1[0] # doubt
dict1

AttributeError: 'dict' object attribute 'keys' is read-only

In [5]:
import pandas as pd
df = pd.read_csv(movies_path) 
df.head()

Movie ID                                Movie Title  Release Year  Runtime  \
0         1   Harry Potter and the Philosopher's Stone          2001      152   
1         2    Harry Potter and the Chamber of Secrets          2002      161   
2         3   Harry Potter and the Prisoner of Azkaban          2004      142   
3         4        Harry Potter and the Goblet of Fire          2005      157   
4         5  Harry Potter and the Order of the Phoenix          2007      138   

          Budget       Box Office  
0  $125,000,000   $1,002,000,000   
1  $100,000,000     $880,300,000   
2  $130,000,000     $796,700,000   
3  $150,000,000     $896,400,000   
4  $150,000,000     $942,000,000

In [11]:
df["text"] = "Box office collection of movie - " + df['Movie Title'] + " is " + df['Box Office']
# for i, r in df.iterrows():
df.head()


Movie ID                                Movie Title  Release Year  Runtime  \
0         1   Harry Potter and the Philosopher's Stone          2001      152   
1         2    Harry Potter and the Chamber of Secrets          2002      161   
2         3   Harry Potter and the Prisoner of Azkaban          2004      142   
3         4        Harry Potter and the Goblet of Fire          2005      157   
4         5  Harry Potter and the Order of the Phoenix          2007      138   

          Budget       Box Office  \
0  $125,000,000   $1,002,000,000    
1  $100,000,000     $880,300,000    
2  $130,000,000     $796,700,000    
3  $150,000,000     $896,400,000    
4  $150,000,000     $942,000,000    

                                                text  
0  Box office collection of movie - Harry Potter ...  
1  Box office collection of movie - Harry Potter ...  
2  Box office collection of movie - Harry Potter ...  
3  Box office collection of movie - Harry Potter ...  
4  Box office collection of movie - Harry Potter ...

In [17]:
corpus = list(df['text'])

In [19]:
from transformers import pipeline

In [21]:
classifier = pipeline('text-classification')
classifier(" Ramesh is a good boy")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9998072981834412}]

In [23]:
classifier(corpus)

[{'label': 'POSITIVE', 'score': 0.9982427358627319},
 {'label': 'POSITIVE', 'score': 0.997869610786438},
 {'label': 'POSITIVE', 'score': 0.9964237809181213},
 {'label': 'POSITIVE', 'score': 0.9981662631034851},
 {'label': 'POSITIVE', 'score': 0.9979549646377563},
 {'label': 'POSITIVE', 'score': 0.9974629878997803},
 {'label': 'POSITIVE', 'score': 0.9977529644966125},
 {'label': 'POSITIVE', 'score': 0.9982642531394958}]

In [24]:
text

'\ufeffMovie ID,Movie Title,Release Year,Runtime,Budget,Box Office\n1,Harry Potter and the Philosopher\'s Stone,2001,152,"$125,000,000 ","$1,002,000,000 "\n2,Harry Potter and the Chamber of Secrets,2002,161,"$100,000,000 ","$880,300,000 "\n3,Harry Potter and the Prisoner of Azkaban,2004,142,"$130,000,000 ","$796,700,000 "\n4,Harry Potter and the Goblet of Fire,2005,157,"$150,000,000 ","$896,400,000 "\n5,Harry Potter and the Order of the Phoenix,2007,138,"$150,000,000 ","$942,000,000 "\n6,Harry Potter and the Half-Blood Prince,2009,153,"$250,000,000 ","$943,200,000 "\n7,Harry Potter and the Deathly Hallows Part 1,2010,146,"$200,000,000 ","$976,900,000 "\n8,Harry Potter and the Deathly Hallows Part 2,2011,130,"$250,000,000 ","$1,342,000,000 "\n'

In [ ]:
pipeline ==> auto tokenizer + automodel

In [67]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [68]:
model_id = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [69]:
tok_1 = tokenizer("Ramesh is a good boy", return_tensors='pt')

In [44]:
tok_1.to('cuda')
# AssertionError: Torch not compiled with CUDA enabled
# Above error is thrown when cuda is not an object

AssertionError: Torch not compiled with CUDA enabled

In [70]:
print(tok_1)
type(tok_1)

{'input_ids': tensor([[ 101, 8223, 9953, 2003, 1037, 2204, 2879,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}


transformers.tokenization_utils_base.BatchEncoding

In [35]:
import torch
torch.tensor(tok_1['input_ids'])

tensor([ 101, 8223, 9953, 2003, 1037, 2204, 2879,  102])

In [71]:
model = AutoModelForSequenceClassification.from_pretrained(model_id)

In [81]:
print(**tok_1)

TypeError: 'input_ids' is an invalid keyword argument for print()

In [73]:
output = model(**tok_1)
# model("Ramesh is a boy")
output

SequenceClassifierOutput(loss=None, logits=tensor([[-4.0886,  4.4654]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [74]:
logits = output.logits
logits

tensor([[-4.0886,  4.4654]], grad_fn=<AddmmBackward0>)

In [78]:
print(logits.argmax())
print(logits.argmax().item())

tensor(1)
1


In [ ]:
# https://huggingface.co/docs/transformers/main/en/model_doc/distilbert#transformers.DistilBertForSequenceClassification
import torch
from transformers import AutoTokenizer, DistilBertForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")              
# instance of tokenizer object which takes in  input as text
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")
# instence of model object in--token id(input_id and attention mask)====== output as label id
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
# output dict with input_id and attention mask
with torch.no_grad():
    logits = model(**inputs).logits
# output of model contains logits and some other outputs so picking only logits
predicted_class_id = logits.argmax().item()

# To train a model on `num_labels` classes, you can pass `num_labels=num_labels` to `.from_pretrained(...)`
num_labels = len(model.config.id2label)
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=num_labels)
labels = torch.tensor([1])
loss = model(**inputs, labels=labels).loss

In [90]:
num_labels = len(model.config.id2label)
num_labels

2

In [94]:
model.config

DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.39.2",
  "vocab_size": 30522
}

In [ ]:
import torch
from transformers import AutoTokenizer, DistilBertForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", problem_type="multi_label_classification")

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_ids = torch.arange(0, logits.shape[-1])[torch.sigmoid(logits).squeeze(dim=0) > 0.5]

# To train a model on `num_labels` classes, you can pass `num_labels=num_labels` to `.from_pretrained(...)`
num_labels = len(model.config.id2label)
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=num_labels, problem_type="multi_label_classification"
)

labels = torch.sum(
    torch.nn.functional.one_hot(predicted_class_ids[None, :].clone(), num_classes=num_labels), dim=1
).to(torch.float)
loss = model(**inputs, labels=labels).loss

In [95]:
predicted_class_ids = torch.arange(0, logits.shape[-1])[torch.sigmoid(logits).squeeze(dim=0) > 0.5]
predicted_class_ids

tensor([1])

In [ ]:
# review how kwargs happen # Home work - why we use ** in (    logits = model(**inputs).logits)

In [51]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_tokens',
 '_additional_special_tokens',
 '_auto_class',
 '_batch_encode_plus',
 '_bos_token',
 '_call_one',
 '_cls_token',
 '_compile_jinja_template',
 '_convert_encoding',
 '_convert_id_to_token',
 '_convert_token_to_id_with_added_voc',
 '_create_repo',
 '_decode',
 '_decode_use_source_tokenizer',
 '_encode_plus',
 '_eos_token',
 '_eventual_warn_about_too_long_sequence',
 '_eventually_correct_t5_max_length',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_mask_token',
 '

In [52]:
tokenizer.tokenize("Ramesh is a boy")

['ram', '##esh', 'is', 'a', 'boy']

In [82]:
#func to take in 3 args and add them
def add_3(a,b,c):
   return a+b+c

In [83]:
x = 2
y = 5
z = 7

add_3(x,y,z)

14

In [84]:
add_3(a=x,b=y,c=z)

14

In [85]:
dic1={'a':x,
      'b':y,
      'c':z
      }
dic1

{'a': 2, 'b': 5, 'c': 7}

In [86]:
dic2 = dict(a=x, b=y, c=z)
dic2

{'a': 2, 'b': 5, 'c': 7}

In [88]:
dic_3 = dict(**dic1)
dic_3

{'a': 2, 'b': 5, 'c': 7}

In [87]:
add_3(**dic2)

14