## Methods

In [3]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [5]:
a = torch.tensor([1])
print(a)
b = torch.tensor([4])
b

tensor([1])


tensor([4])

In [6]:
ar = torch.zeros([3])
ar

tensor([0., 0., 0.])

In [9]:
a0 = torch.zeros([3,4])
print(a0)
a0.shape


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.Size([3, 4])

In [10]:
as1 = torch.ones(3,2)
print(as1)
arand = torch.rand(3,4)
arand

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[0.5290, 0.3358, 0.6869, 0.9866],
        [0.0244, 0.0178, 0.3183, 0.1810],
        [0.5687, 0.9986, 0.1377, 0.7378]])

In [11]:
aemp = torch.empty(2,3)
aemp

tensor([[ 9.1477e-41,  0.0000e+00,  1.3452e-43],
        [ 0.0000e+00, -8.1922e+03,  4.5862e-41]])

In [14]:
randa = torch.randint(high=12, low=6, size=[3,4])
randa

tensor([[ 7,  9,  9,  8],
        [ 6,  7,  6,  7],
        [ 9,  7, 11,  8]])

In [20]:
n = torch.tensor([65.43])

print(n<0)
print(n>0)

print((n < 0).long())
print((n > 0).long())


tensor([False])
tensor([True])
tensor([0])
tensor([1])


In [23]:
torch.where(torch.tensor(False), torch.tensor(1), torch.tensor(0))

tensor(0)

In [25]:
print(randa)
torch.where(randa > 10, torch.tensor(567), torch.tensor(63))

tensor([[ 7,  9,  9,  8],
        [ 6,  7,  6,  7],
        [ 9,  7, 11,  8]])


tensor([[ 63,  63,  63,  63],
        [ 63,  63,  63,  63],
        [ 63,  63, 567,  63]])

In [27]:
n_3r = torch.tensor([5.7, 62, 46])
print(n_3r.shape)
n_3c = torch.tensor([[5],[7],[1]])
print(n_3c.shape)
n_3rc = torch.tensor([[3, 4, 5]])
print(n_3rc.shape)

torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3])


In [29]:
a0like = torch.zeros_like(randa)
print(a0like)

a1like = torch.ones_like(randa)
print(a1like)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [31]:
# making tensors of random numbers
try:
    arandlike = torch.rand_like(torch.tensor([1, 5, 7]))
except Exception as e:
    print(e)
    
arandlike = torch.rand_like(torch.tensor([1.5, 5.2, 77.5]))
arandlike

"check_uniform_bounds" not implemented for 'Long'


tensor([0.5486, 0.4106, 0.1831])

In [32]:
arandlike = torch.rand_like(torch.tensor([1, 5, 7]))


RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [33]:
import numpy as np

rangenum = np.linspace(5,19,10)
rangenum

array([ 5.        ,  6.55555556,  8.11111111,  9.66666667, 11.22222222,
       12.77777778, 14.33333333, 15.88888889, 17.44444444, 19.        ])

In [35]:
rangets = torch.linspace(5,19,10)
rangets


tensor([ 5.0000,  6.5556,  8.1111,  9.6667, 11.2222, 12.7778, 14.3333, 15.8889,
        17.4444, 19.0000])

In [36]:
h = torch.eye(5)
h

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [38]:
h1 = torch.rand(size= [199,57,66])
print(h1)
print(h1.shape)
print(h1[0].shape)
print(h1[0][0].shape)

tensor([[[0.2446, 0.8012, 0.4593,  ..., 0.2071, 0.8065, 0.5329],
         [0.2194, 0.5919, 0.1504,  ..., 0.3340, 0.1386, 0.7412],
         [0.4578, 0.6065, 0.2774,  ..., 0.6390, 0.5760, 0.9973],
         ...,
         [0.0761, 0.9789, 0.8705,  ..., 0.8140, 0.8399, 0.5644],
         [0.5740, 0.5844, 0.8958,  ..., 0.1667, 0.8461, 0.5011],
         [0.7874, 0.8376, 0.5795,  ..., 0.4177, 0.8985, 0.6112]],

        [[0.1282, 0.0703, 0.3182,  ..., 0.3222, 0.1267, 0.9810],
         [0.7494, 0.8415, 0.6890,  ..., 0.3192, 0.2293, 0.9516],
         [0.9372, 0.5954, 0.9073,  ..., 0.5777, 0.7945, 0.6816],
         ...,
         [0.2587, 0.5729, 0.7532,  ..., 0.3931, 0.6413, 0.7946],
         [0.9009, 0.8711, 0.6035,  ..., 0.5305, 0.9193, 0.5402],
         [0.0814, 0.8222, 0.0502,  ..., 0.8866, 0.2472, 0.3453]],

        [[0.3183, 0.6032, 0.1082,  ..., 0.5978, 0.5545, 0.3205],
         [0.5977, 0.5783, 0.3207,  ..., 0.4012, 0.3091, 0.3655],
         [0.7068, 0.2024, 0.6518,  ..., 0.7068, 0.1921, 0.

In [40]:
ys = torch.rand(3)
print(ys)
print(ys.shape)

tensor([0.2992, 0.3614, 0.5616])
torch.Size([3])


In [41]:
us = ys.unsqueeze(dim=0)
print(us)
print(us.shape)

tensor([[0.2992, 0.3614, 0.5616]])
torch.Size([1, 3])


In [42]:
us = ys.unsqueeze(dim=1)
print(us)
print(us.shape)

tensor([[0.2992],
        [0.3614],
        [0.5616]])
torch.Size([3, 1])


In [136]:
ys123 = torch.rand(4,1,3)
print(ys123)
print(ys123[2][0][2])

tensor([[[0.7438, 0.6384, 0.5963]],

        [[0.2702, 0.7338, 0.0466]],

        [[0.2596, 0.7646, 0.5064]],

        [[0.9306, 0.3998, 0.0830]]])
tensor(0.5064)


In [137]:
sqys123 = torch.squeeze(ys123)
print(ys123.shape)
print(sqys123.shape)

torch.Size([4, 1, 3])
torch.Size([4, 3])


In [43]:
ys1 = torch.rand(3,2)
print(ys1)
print(ys1.unsqueeze(dim=0))
print(ys1.unsqueeze(dim=0).shape)
print(ys1.unsqueeze(dim=1))
print(ys1.unsqueeze(dim=1).shape)

tensor([[0.3668, 0.3776],
        [0.2720, 0.1192],
        [0.4105, 0.1680]])
tensor([[[0.3668, 0.3776],
         [0.2720, 0.1192],
         [0.4105, 0.1680]]])
torch.Size([1, 3, 2])
tensor([[[0.3668, 0.3776]],

        [[0.2720, 0.1192]],

        [[0.4105, 0.1680]]])
torch.Size([3, 1, 2])


In [44]:
ys1 = torch.rand(3,2)
print(ys1)
print(ys1.squeeze(dim=0))
print(ys1.squeeze(dim=0).shape)
print(ys1.squeeze(dim=1))
print(ys1.squeeze(dim=1).shape)

tensor([[0.6267, 0.8758],
        [0.9457, 0.1839],
        [0.3365, 0.8620]])
tensor([[0.6267, 0.8758],
        [0.9457, 0.1839],
        [0.3365, 0.8620]])
torch.Size([3, 2])
tensor([[0.6267, 0.8758],
        [0.9457, 0.1839],
        [0.3365, 0.8620]])
torch.Size([3, 2])


In [47]:
j = torch.tensor([0.2, 8.5, 3.25])
samples = torch.multinomial(j, 10, replacement = True)
samples

tensor([0, 1, 1, 1, 2, 1, 2, 2, 1, 1])

In [51]:
m2 = torch.tensor([[5, 0, 1],
                   [8, 10, 9],
                   [0.5, 0.7, 0.9]])
print(m2)
p2 = torch.multinomial(m2, 5, True)
print(p2)

tensor([[ 5.0000,  0.0000,  1.0000],
        [ 8.0000, 10.0000,  9.0000],
        [ 0.5000,  0.7000,  0.9000]])
tensor([[0, 0, 0, 0, 2],
        [2, 2, 0, 2, 0],
        [1, 0, 1, 2, 1]])


In [107]:
k = torch.tensor([[1,2,5,7]])
l = torch.tensor([[5,6,7,8]])
m = torch.tensor(5)
print(k)
print(l)
print(m)

tensor([[1, 2, 5, 7]])
tensor([[5, 6, 7, 8]])
tensor(5)


In [108]:
print(k.shape)


torch.Size([1, 4])


In [112]:
outcat = torch.cat((k,l), dim=0) # dim =1 ==>tensor([[1, 2, 5, 7, 5]])

outcat

tensor([[1, 2, 5, 7],
        [5, 6, 7, 8]])

In [ ]:
try:
    outcol = torch.cat((k, m), dim=1)
    outcol
except Exception as e:
    print(e)

p = torch.randint(low=5, high=10, size=(2, 5))
q = torch.randint(low=10, high=100, size=(2, 5))
outcol = torch.cat((p, q), dim=1)
outcol

zero-dimensional tensor (at position 1) cannot be concatenated


tensor([[ 8,  8,  5,  5,  9, 97, 67, 96, 56, 55],
        [ 9,  9,  9,  9,  6, 63, 92, 52, 38, 78]])

In [55]:
s1 = torch.arange(0,5)
s1

tensor([0, 1, 2, 3, 4])

In [120]:
s1 = torch.arange(0, 5)  # all tensors are 1r and 5c shape
s2 = torch.arange(1, 6)
s3 = torch.arange(2, 7)
s4 = torch.arange(4, 9)
try:
    s5 = torch.stack(s1, s2, s3, s4)
except Exception as e:
    print(e)
s5 = torch.stack([s1, s2, s3, s4])
print(s5)
print(s5.shape)


stack() takes from 1 to 2 positional arguments but 4 were given
tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8]])
torch.Size([4, 5])


In [116]:
s6 = torch.cat((s1,s2,s3,s4),dim=1)
s6

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [122]:
s5 = torch.stack([s1, s2, s3, s4], dim=1)
print(s5)
print(s5.shape)


tensor([[0, 1, 2, 4],
        [1, 2, 3, 5],
        [2, 3, 4, 6],
        [3, 4, 5, 7],
        [4, 5, 6, 8]])
torch.Size([5, 4])


In [66]:
print(type(s5))
# print(torch.transpose(s5)) #TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
print(s5.transpose(0,1))

<class 'torch.Tensor'>
tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8]])


In [68]:
tlo = torch.tril(torch.ones(5,5))
tlo

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [69]:
tup = torch.triu(torch.ones(5, 5) * 5)
tup

tensor([[5., 5., 5., 5., 5.],
        [0., 5., 5., 5., 5.],
        [0., 0., 5., 5., 5.],
        [0., 0., 0., 5., 5.],
        [0., 0., 0., 0., 5.]])

In [81]:
maskout = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0,float('-inf'))
maskout

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [80]:
a = torch.triu(torch.ones(5, 5))== 0,float('-inf')
print(type(a))
print(a)

<class 'tuple'>
(tensor([[False, False, False, False, False],
        [ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False]]), -inf)


In [82]:
torch.exp(maskout)


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [83]:
# transpose

input = torch.rand(5, 6, 2)
print(input.shape)
inputout = input.transpose(0, 1)
inputout.shape

torch.Size([5, 6, 2])


torch.Size([6, 5, 2])

## Functional

In [139]:
import torch.nn.functional as F
import torch
import torch.nn as nn

In [141]:
te1 = torch.tensor([1,2,3], dtype=torch.float32)
te1

tensor([1., 2., 3.])

In [92]:
lin1 = nn.Linear(3,1,bias=False)
lin2 = nn.Linear(1,1, bias = False)

In [97]:
print(lin1)
print(lin1.parameters())

Linear(in_features=3, out_features=1, bias=False)
<generator object Module.parameters at 0x7fd8c879fc80>


In [93]:
out1 = lin1(te1)
out1

tensor([-0.3154], grad_fn=<SqueezeBackward4>)

In [95]:
out2 = lin2(out1)
out2

tensor([-0.1038], grad_fn=<SqueezeBackward4>)

In [142]:
s = F.softmax(te1)
s

/var/folders/m_/_x8t4kvn0334z53zdz_86l400000gp/T/ipykernel_33977/2936821666.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  s = F.softmax(te1)


tensor([0.0900, 0.2447, 0.6652])

In [144]:
# softmax sums to 1.0
s.sum()

tensor(1.)

In [218]:
vocab_size = 80
# emb_size = 6
emb_size = 784

r_in = nn.Embedding(num_embeddings=vocab_size, embedding_dim=emb_size)
new_te1 = torch.LongTensor([12, 8, 5, 0])
eout = r_in(new_te1)
print(eout.shape)
print(eout)

torch.Size([4, 784])
tensor([[-0.5376,  1.3717,  0.6831,  ...,  1.9719, -0.6089,  0.4366],
        [ 3.8722, -1.6887,  0.8647,  ...,  1.5689,  0.7199, -0.8095],
        [ 0.8732,  0.5119,  0.3155,  ..., -1.0118, -0.4362, -0.4794],
        [-1.5798, -0.7354,  0.3107,  ..., -0.2928, -0.9529, -0.8576]],
       grad_fn=<EmbeddingBackward0>)


In [214]:
# torch.randint(low=4, high=18, size=(1,4))
torch.linspace(3,8,6)

tensor([3., 4., 5., 6., 7., 8.])

In [224]:
ex1 = torch.tensor([0], dtype =torch.int32)
ex1
outp=r_in(ex1)
outp

tensor([[-1.5798e+00, -7.3538e-01,  3.1068e-01, -4.8963e-01, -1.3874e+00,
          7.2356e-02, -1.9512e+00, -2.4721e-02,  1.4559e-01,  8.3897e-02,
          2.4256e-01,  8.8669e-01, -1.0295e+00,  1.7729e-01, -7.4582e-01,
          2.7761e-01,  1.7317e+00,  7.1764e-01,  2.6918e-01,  5.7215e-01,
         -6.8779e-01, -1.3057e-01, -4.6329e-01,  1.7224e+00,  4.7065e-01,
          1.6437e+00,  1.6987e+00,  4.6319e-01, -6.3856e-01,  1.5659e+00,
         -1.3526e+00, -1.0006e-01,  1.1381e+00,  5.7479e-01,  2.9670e-01,
         -2.9718e-01, -1.8556e+00,  1.0386e+00, -7.2160e-01, -2.5542e+00,
         -6.6307e-01,  5.9296e-01,  3.3716e-02,  1.1445e+00, -1.0741e+00,
          2.6674e-01, -1.1602e+00, -7.8298e-01,  1.8680e+00, -2.3353e-01,
         -7.8968e-02,  5.6062e-01, -3.4823e-01,  9.2666e-01, -5.3068e-01,
          1.2467e+00, -4.3039e-01,  2.9230e-03, -6.6415e-01,  5.4997e-01,
          2.1429e+00, -1.6650e+00,  2.9356e+00,  7.3765e-01, -4.0848e-01,
         -2.2729e-01, -3.3998e-01,  1.

In [226]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('distilbert/distilbert-base-uncased-finetuned-sst-2-english')
vocab_size_distilber=30522
print(tokenizer)

DistilBertTokenizerFast(name_or_path='distilbert/distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}


In [227]:
db_emb = nn.Embedding(num_embeddings = vocab_size_distilber, embedding_dim=384)
db_emb

Embedding(30522, 384)

In [228]:
sent = "we are testing embeddings for the first time"
sent_tokens = tokenizer(sent, return_tensors='pt')
print(sent_tokens['input_ids'])

tensor([[ 101, 2057, 2024, 5604, 7861, 8270, 4667, 2015, 2005, 1996, 2034, 2051,
          102]])


In [229]:
db_emb(sent_tokens['input_ids'])

tensor([[[ 0.6918, -1.9705,  0.3291,  ..., -0.7998, -3.1324,  0.2211],
         [-0.8938,  1.6910,  0.1237,  ..., -0.1077,  1.3064,  0.0846],
         [-0.4536,  0.9506, -1.0150,  ...,  1.0822, -0.2433, -0.0779],
         ...,
         [-0.1170, -0.0227,  1.0186,  ...,  2.0562, -0.0242,  0.6398],
         [-0.0716, -0.1697, -0.4133,  ...,  1.2634, -0.0077, -0.9388],
         [ 0.2548,  0.5899,  1.7038,  ...,  0.4848, -0.3463, -0.5861]]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
# take a data set and use mapping to create embeddings and compare without mapping

In [217]:
new_te2 = torch.linspace(3,8,6, dtype=torch.int)
print(new_te2)
eout2 = r_in(new_te2)
print(eout2.shape)
print(eout2)

tensor([3, 4, 5, 6, 7, 8], dtype=torch.int32)
torch.Size([6, 6])
tensor([[ 2.0871,  0.2693, -0.2372, -0.7070,  1.4054,  0.5916],
        [-1.9891,  0.6110, -0.4201, -1.6939,  0.2827,  0.6559],
        [-1.4677,  0.0138, -0.7707, -1.0284, -0.2682, -0.2340],
        [-1.8330,  0.2829,  0.3154,  0.5179, -0.9329,  1.4112],
        [-0.0701,  0.3991, -0.7764, -1.2926, -2.4103, -0.1897],
        [ 1.0619, -0.7392,  0.4594, -0.6055, -1.0341,  0.2355]],
       grad_fn=<EmbeddingBackward0>)


In [147]:
a = torch.tensor([[1, 2], [2, 3], [3, 4], [4, 5]])
b = torch.tensor([[7, 6, 2], [6, 3, 4]])

print(a @ b) 

tensor([[19, 12, 10],
        [32, 21, 16],
        [45, 30, 22],
        [58, 39, 28]])


In [149]:
input = torch.rand(2,3,8)

n,r,c = input.shape
print(n,r,c)
output = input.view(n*r,c)
print(output.shape)

2 3 8
torch.Size([6, 8])


In [150]:
print(input)
print(output)

tensor([[[0.2169, 0.7580, 0.4977, 0.6913, 0.9418, 0.9474, 0.4893, 0.4242],
         [0.7699, 0.0595, 0.1064, 0.5097, 0.2571, 0.4381, 0.1050, 0.7029],
         [0.2340, 0.7783, 0.2890, 0.1575, 0.0092, 0.3530, 0.0209, 0.0807]],

        [[0.4697, 0.7373, 0.4587, 0.5898, 0.1385, 0.5877, 0.7840, 0.6525],
         [0.5178, 0.5769, 0.3043, 0.5954, 0.3512, 0.4245, 0.2480, 0.0374],
         [0.5843, 0.8717, 0.9643, 0.5455, 0.3535, 0.9158, 0.7526, 0.6518]]])
tensor([[0.2169, 0.7580, 0.4977, 0.6913, 0.9418, 0.9474, 0.4893, 0.4242],
        [0.7699, 0.0595, 0.1064, 0.5097, 0.2571, 0.4381, 0.1050, 0.7029],
        [0.2340, 0.7783, 0.2890, 0.1575, 0.0092, 0.3530, 0.0209, 0.0807],
        [0.4697, 0.7373, 0.4587, 0.5898, 0.1385, 0.5877, 0.7840, 0.6525],
        [0.5178, 0.5769, 0.3043, 0.5954, 0.3512, 0.4245, 0.2480, 0.0374],
        [0.5843, 0.8717, 0.9643, 0.5455, 0.3535, 0.9158, 0.7526, 0.6518]])


In [151]:
b = torch.randint(1, 75, size=(2, 8))
d = torch.randint(1, 75, size=(2, 8))
print(b)
print(d)

tensor([[44, 18, 61, 53, 40, 65, 43, 26],
        [16, 53,  5, 39, 70, 45, 44, 31]])
tensor([[39, 74, 70, 47, 32, 74, 45, 65],
        [63, 72, 25, 45, 70, 44, 27, 57]])


In [153]:
b = torch.tensor(torch.randint(1, 75, size=(2, 8)), dtype=torch.float32)
d = torch.tensor(torch.randint(1, 75, size=(2, 8)), dtype=torch.float32) 
print(b)
print(d)

tensor([[51., 27., 26., 46., 26.,  4., 62.,  7.],
        [42.,  4.,  5., 27., 48., 24., 53., 10.]])
tensor([[19., 69., 52., 72., 58., 29.,  2., 13.],
        [34., 24., 70.,  9.,  9.,  9., 18., 26.]])


/var/folders/m_/_x8t4kvn0334z53zdz_86l400000gp/T/ipykernel_33977/781537471.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(torch.randint(1, 75, size=(2, 8)), dtype=torch.float32)
/var/folders/m_/_x8t4kvn0334z53zdz_86l400000gp/T/ipykernel_33977/781537471.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  d = torch.tensor(torch.randint(1, 75, size=(2, 8)), dtype=torch.float32)


In [154]:
bf = b.float() 
bf.dtype
df = d.float()

In [156]:
df.view(2 * 8)
# df

tensor([19., 69., 52., 72., 58., 29.,  2., 13., 34., 24., 70.,  9.,  9.,  9.,
        18., 26.])

In [157]:
ce = F.cross_entropy(bf.view(16), df.view(16))
ce

tensor(18492.0723)

In [231]:
from sklearn import datasets

wineds = datasets.load_wine()
# print(wineds.shape)
print(type(wineds))
data = wineds['data']
print(data.shape)
tgt = wineds['target']
tgt.shape

<class 'sklearn.utils._bunch.Bunch'>
(178, 13)


(178,)

In [234]:
for i,x in wineds.items():
    print(i)
    print(type(x))

data
<class 'numpy.ndarray'>
target
<class 'numpy.ndarray'>
frame
<class 'NoneType'>
target_names
<class 'numpy.ndarray'>
DESCR
<class 'str'>
feature_names
<class 'list'>


In [ ]:
# get the data from sklearn datasets, shape 178,13==> dict==> with data and tgt
# convert the data from numpy to tensors torch using class Winedataset which inherits datasets class from torch.utils.data
# load the dataset using dataloader with batch size = 3
# 

In [165]:
import numpy as np
x_data = np.linspace(50, 686, 250)
x_data.shape

(250,)

In [168]:
x_tensor = torch.from_numpy(x_data.astype(np.float32))
x_tensor.shape
x_tensor.dtype

torch.float32

In [172]:
from torch.utils.data import Dataset, DataLoader

class WineDataset(Dataset):
    def __init__(self, x_data, y_data):
        self.x = torch.from_numpy(x_data.astype(np.float32))
        self.y = torch.from_numpy(y_data.astype(np.float32))
        self.n_samples = x_data.shape[0]
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    def __len__(self):
        return self.n_samples
        

In [173]:
wineds = WineDataset(x_data=data,
                     y_data=tgt)
wineds[2]

(tensor([1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
         3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
         1.1850e+03]),
 tensor(0.))

In [175]:
wine_dl = DataLoader(wineds, shuffle=True, batch_size=3)
dloader_iter = iter(wine_dl)

In [176]:
next(dloader_iter)


[tensor([[1.2000e+01, 3.4300e+00, 2.0000e+00, 1.9000e+01, 8.7000e+01, 2.0000e+00,
          1.6400e+00, 3.7000e-01, 1.8700e+00, 1.2800e+00, 9.3000e-01, 3.0500e+00,
          5.6400e+02],
         [1.3390e+01, 1.7700e+00, 2.6200e+00, 1.6100e+01, 9.3000e+01, 2.8500e+00,
          2.9400e+00, 3.4000e-01, 1.4500e+00, 4.8000e+00, 9.2000e-01, 3.2200e+00,
          1.1950e+03],
         [1.3050e+01, 2.0500e+00, 3.2200e+00, 2.5000e+01, 1.2400e+02, 2.6300e+00,
          2.6800e+00, 4.7000e-01, 1.9200e+00, 3.5800e+00, 1.1300e+00, 3.2000e+00,
          8.3000e+02]]),
 tensor([1., 0., 0.])]

In [177]:
x = torch.empty(5,6,7)
y = torch.empty(5,6,7)


In [180]:
x = torch.empty((0, ))
x = torch.empty(2, 2)

a = torch.rand((3, 3, 1))
b = torch.rand((3, 1))


In [ ]:
# tensor of same shapes are broadcastable
# Broadcastable ??

# In above example tensor T2 shape (3,1) has one in its back dimension and tension T1 (3,3) don’t have any one in its dimension . 
# So, We have to broadcast along the dimension where the tensor dimension is 1 to match the corresponding dimension of the other tensor T1.

In [184]:
# When it comes to Matrix Multiplication, there are following pairs one has to identify
# vector * vector, matrix * vector, batched mat * vector(bc) 
# batched matrix * batched matrix, batched matrix * broadcasted matrix
# A vector is of shape 1 row n col

# vector X vector is acceptable, and return dot product
tensor2 = torch.rand(3)  # Size([3]) 

tensor1 = torch.tensor([5, 6, 8], dtype=torch.float32)  # Size([3])

tensor1 @ tensor2  # returns dot-pdt

tensor(6.7755)

In [185]:
matensor = torch.tensor([[1, 3, 4,],
                         [5, 7, 6,],
                         [9, 2, 8]],
                         dtype=torch.float32)

tensor2 @ matensor  # 1D to 2D is processed

tensor([5.6682, 5.3502, 6.5811])

In [186]:
tensor5 = torch.rand(3, 3, 4)
tensor6 = torch.rand(4)

tensor5 @ tensor6 # batched tensor broadcasts over vectors

tensor([[0.4579, 0.6261, 0.6651],
        [0.5829, 0.3901, 0.2865],
        [0.3877, 0.5067, 0.1535]])

In [189]:
tensor7 = torch.rand(2,3,3)
tensor8 = torch.rand(2,3,3)
print(tensor7)
print(tensor7 @ tensor8)
(tensor7 @ tensor8).shape


tensor([[[0.8014, 0.0525, 0.9832],
         [0.4184, 0.2516, 0.4690],
         [0.1283, 0.0737, 0.4402]],

        [[0.5293, 0.2953, 0.0341],
         [0.7695, 0.8032, 0.2560],
         [0.6585, 0.3636, 0.9774]]])
tensor([[[1.2398, 1.2223, 0.7674],
         [0.7292, 0.6151, 0.4099],
         [0.4932, 0.4500, 0.3372]],

        [[0.6754, 0.7720, 0.5152],
         [1.3437, 1.5441, 1.0777],
         [1.5373, 1.4577, 1.4480]]])


torch.Size([2, 3, 3])

In [191]:
flatten = nn.Flatten(start_dim=0, end_dim=-1)
print(tensor8.shape)
x = flatten(tensor8)
x.shape

torch.Size([2, 3, 3])


torch.Size([18])

In [193]:
flatten = nn.Flatten(start_dim=0, end_dim=-2)
print(tensor8.shape)
x = flatten(tensor8)
x.shape

torch.Size([2, 3, 3])


torch.Size([6, 3])

In [194]:
flaten = nn.Flatten(start_dim=1, end_dim=-1)
# -1 means the final value is calculated by torch
test_data2 = torch.rand(5, 28, 28)
test_out = flaten(test_data2)  # Size([5, 784])

print(test_out.shape)  # Size([5, 784])

torch.Size([5, 784])


In [195]:
l1 = nn.Linear(784, 2)
l1(test_out)


tensor([[-0.0887, -0.5747],
        [-0.0456, -0.5921],
        [-0.2420, -0.4732],
        [-0.1538, -0.2757],
        [ 0.0569, -0.3440]], grad_fn=<AddmmBackward0>)

In [196]:
r1 = nn.ReLU()
hi2 = r1(l1(test_out))
hi2

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0569, 0.0000]], grad_fn=<ReluBackward0>)

In [197]:
seq2 = nn.Sequential(
    flaten,
    nn.Linear(784, 512),
    r1,
    nn.Linear(512, 512),
    r1,
    nn.Linear(512, 10)
)
print(seq2(test_out).shape)
seq2(test_out)

torch.Size([5, 10])


tensor([[-0.0511,  0.0473,  0.0584,  0.0043,  0.0442, -0.0790, -0.0265,  0.0521,
          0.0805,  0.0394],
        [-0.0152,  0.0296,  0.0661,  0.0006,  0.0241, -0.0941, -0.0817,  0.0735,
          0.1138,  0.0345],
        [-0.0289,  0.0015,  0.0601,  0.0128, -0.0128, -0.1033, -0.0774,  0.0901,
          0.0806,  0.0221],
        [-0.0425, -0.0035,  0.0678,  0.0234,  0.0340, -0.1007, -0.0246,  0.0715,
          0.0536,  0.1009],
        [-0.0608,  0.0428,  0.1092, -0.0086,  0.0071, -0.1028, -0.0586,  0.1175,
          0.0768,  0.0307]], grad_fn=<AddmmBackward0>)

In [198]:
for name, params in seq2.named_parameters():
    print(f'Layer: {name} | size: {params.size()} | vals : {params[:2]}')

Layer: 1.weight | size: torch.Size([512, 784]) | vals : tensor([[-0.0096, -0.0342,  0.0141,  ...,  0.0002,  0.0021,  0.0152],
        [-0.0066,  0.0160,  0.0076,  ..., -0.0033,  0.0058,  0.0074]],
       grad_fn=<SliceBackward0>)
Layer: 1.bias | size: torch.Size([512]) | vals : tensor([0.0300, 0.0025], grad_fn=<SliceBackward0>)
Layer: 3.weight | size: torch.Size([512, 512]) | vals : tensor([[ 0.0116,  0.0386,  0.0078,  ...,  0.0205,  0.0296, -0.0076],
        [ 0.0204, -0.0284, -0.0371,  ...,  0.0164, -0.0263, -0.0039]],
       grad_fn=<SliceBackward0>)
Layer: 3.bias | size: torch.Size([512]) | vals : tensor([0.0222, 0.0004], grad_fn=<SliceBackward0>)
Layer: 5.weight | size: torch.Size([10, 512]) | vals : tensor([[-0.0069, -0.0055,  0.0401,  ...,  0.0275, -0.0219,  0.0047],
        [-0.0423,  0.0417, -0.0045,  ...,  0.0125, -0.0406, -0.0157]],
       grad_fn=<SliceBackward0>)
Layer: 5.bias | size: torch.Size([10]) | vals : tensor([ 0.0335, -0.0118], grad_fn=<SliceBackward0>)


In [199]:
# Basic model (need to practice)
x = torch.ones(5)
y = torch.zeros(3)

w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

z = torch.matmul(x, w) + b

loss = F.binary_cross_entropy_with_logits(z, y)
print(loss)

print(f"The z grad fn: {z.grad_fn}")
print(f"The loss grad fn: {loss.grad_fn}")

with torch.no_grad():
    a = torch.matmul(x, w) + b
print(z.requires_grad)  # returns False

f = torch.matmul(x, w) + b
f_det = f.detach()
print(f_det.requires_grad)  # returns false

tensor(0.7658, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
The z grad fn: <AddBackward0 object at 0x7fd8c8812730>
The loss grad fn: <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fd8c87a1d60>
True
False


## Model Training